hobbyfarm/ui

src/app/scenario/ctr.component.ts, src/app/scenario/step.component.ts
=> Ebauman fix token issue

src/app/scenario/scenario.component.ts
=> better chaining to avoid sub-in-sub

src/app/app.component.css, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/services/user.service.spec.ts, src/app/services/user.service.ts
=> password change functionality

package-lock.json, src/app/app.component.html, src/app/app.component.ts, src/app/services/user.service.ts
=> Access code management

src/app/login/login.component.css
These changes should solve issue #2.
=> center and cover login background image

angular.json, package-lock.json, package.json, src/app/VMClaim.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.scss, src/app/scenario/step.component.ts, src/app/scenario/terminal.component.ts, src/app/scenario/vmclaim.component.html, src/app/scenario/vmclaim.component.ts, src/app/services/shell.service.spec.ts, src/app/services/shell.service.ts, src/styles.css, src/styles.scss, src/theme.scss
- New theme! Reskinned to brighten up buttons, change typography, etc. 
- Prevent running of keepalive loop after scenario completion (fixes #33)
- Put finish button in header of step page (fixes #28)
- Added restore logic for websocket connections (kinda fixes #7)
- Added additional status to VM claim page for when machines are being dynamically provisioned
=> v0.3.0 - New UI theme and bugfixes

src/app/scenario/step.component.html, src/app/services/scenario.service.ts
- Finish button was hidden if scenario was not pauseable
- JS error on scenario page if no scenarios found ( fixes #43 )
=> Various fixes

README.md, src/app/scenario/step.component.html, src/app/scenario/step.component.scss
These changes leave the terminal within view after scrolling down the page.
=> Sticky terminal

package-lock.json
Tidying up package management before upgrading things
=> 0.3.1 didn't make it into lock

.github/workflows/publish-image.yaml
This is what happens when you don't test your changes :sweat_smile:
=> fix github action variable name

src/app/home.component.html, src/app/home.component.ts, src/app/scenario/scenario.component.html, src/app/scenario/scenario.component.ts, src/app/scenario/scenariocard.component.ts, src/app/scenario/terminal.component.ts, src/app/scenario/vmclaim.component.html, src/app/scenario/vmclaim.component.ts, src/app/services/session.service.ts
These changes remove the dedicated session page in favor of a modal on the home screen.
=> convert session page to a modal

src/app/app.module.ts
@ebauman, I ran into https://github.com/hobbyfarm/hobbyfarm/issues/89 with some local changes I have and I think these changes fixed it. I haven't tested with the latest release yet but hopefully it'll work for you.
=> use jwt options factory

src/app/scenario/terminal.component.css, src/app/scenario/terminal.component.ts
Signed-off-by: Eamon Bauman <eamon@eamonbauman.com>
Fixes hobbyfarm/hobbyfarm#93
=> fixed terminal scaling

src/app/atob.pipe.ts, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.ts, src/app/services/course.service.ts, src/app/services/scenario.service.ts, src/app/services/session.service.ts, src/app/services/step.service.ts, src/app/services/user.service.ts, src/app/services/vm.service.ts, src/app/services/vmclaim.service.ts, src/app/unicode.ts
Signed-off-by: Eamon Bauman <eamon@eamonbauman.com>
Fixes hobbyfarm/hobbyfarm#100
=> fixed unicode display

src/app/scenario/step.component.html, src/app/scenario/step.component.ts
Signed-off-by: Eamon Bauman <eamon@eamonbauman.com>
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/111
=> fixed vmclaimvm map overwrite issue

package-lock.json
This was supposed to be merged with the Angular 9 /Clarity 3 PR but got missed.
=> fixed package-lock.json

src/app/services/vmclaim.service.ts
=> fixed vmclaim name case

src/app/scenario/step.component.html
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/13
=> Display current stepnumber in scenario

src/app/scenario/step.component.html, src/app/scenario/step.component.ts
=> scroll to top working

src/app/scenario/ctr.component.scss, src/app/scenario/step.component.ts
This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/148
- Adds a scrollbar to overflowing ctr-blocks
- Adds a `target="_blank"` to links in the markdown.
=> Fix for #148

src/app/scenario/step.component.ts
Improve markdown renderer for fenced code blocks. 
**Which issue(s) this PR fixes**:
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/151
=> Quickfix nested markdown

src/app/scenario/terminal.component.ts
Fixes a bug where the wrong command is send to the server when having multiple terminals.
The fix for this is to unsubscribe from the ctrService.
=> Unsubscribe from ctr service to prevent sending the wrong command

src/config.json
Tweak to fix config.json to change the default UI heading to Rancher HobbyFarm
=> Removed Old McDonalds Farm

src/app/app.component.ts, src/app/dynamic-html/module.ts, src/app/home.component.ts, src/app/login/User.ts, src/app/login/login.component.ts, src/app/root.component.ts, src/app/scenario/Scenario.ts, src/app/scenario/ctr.component.ts, src/app/scenario/scenario.component.ts, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts, src/app/scenario/terminal.component.ts, src/app/scenario/vmclaim.component.ts, src/app/scenario/vminfo.component.ts, src/app/scenario/vminfo.service.ts, src/app/services/course.service.ts, src/app/services/session.service.ts, src/app/services/user.service.ts, src/app/services/vmclaim.service.ts, src/app/virtualmachine/vmtemplate.ts
This removes unused imports, variables, methods and modules.
I built and tested the UI with these changes, and I did not notice any breakage.
Fixes svalabs/ui#21
=> Remove dead code

src/app/Session.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts
These are the UI additions needed for https://github.com/hobbyfarm/gargantua/pull/89
It checks of the "Keep VM" Option is set, otherwise VMs will not be kept over the course.
=> Check for option to keep vm for courses

src/app/app.component.html, src/app/app.component.ts, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts
This PR applies code reuse and simplifications to various places that popped up during my ongoing code quality efforts. It also sets all methods to private, that are not used outside of their class.
No functional changes intended. If desired, we can split this PR into smaller chunks of course.
=> DRY and simplify

src/app/course/course.ts, src/app/home.component.html
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/182
=> Fix a bug where keep course vm is ignored

src/app/app-config.service.ts, src/app/auth.guard.ts, src/app/hf-markdown/hf-markdown.component.ts, src/app/home.component.html, src/app/home.component.ts, src/app/scenario/scenario.component.html, src/app/scenario/scenario.component.ts, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts, src/app/scenario/terminal.component.ts, src/app/unicode.ts, tsconfig.json
This PR is a WIP effort to align the strictness of this project's TypeScript configuration with that of a freshly generated Angular 12 project.
Not all strictness options are enabled yet, but this PR could be merged anyway to minimize conflicts. While this is not merged, I might add more changes on top of this.
=> Stricter TypeScript

src/app/app.component.ts, src/app/home.component.html, src/app/home.component.ts, src/app/printable/printable.component.ts, src/app/scenario/ctr.service.ts, src/app/scenario/scenariocard.component.html, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts, src/app/scenario/terminal.component.ts, src/app/services/user.service.ts, tsconfig.json
Continues the work from #122. Based on #124
This leaves only one strictness settings to be enabled, but that last one has a pretty big impact, so I left it out for now.
=> Stricter TypeScript Part 2

.github/workflows/main.yaml, cicd/docker/Dockerfile, cicd/docker/docker-compose-release.yaml, cicd/docker/docker-compose-sdk.yaml
This reduces the amount of code needed for the same CI that we have now.
=> Slim down GH Actions CI

src/app/home.component.html, src/app/scenario/scenariocard.component.html, src/app/services/scenario.service.ts
This PR implements some minor but crucial fixes for the printable feature (e. g. fixing the backend route to gargantua).
=> Printable fixes

src/app/scenario/scenariocard.component.scss
This PR fixes progress bar colors in non-firefox browsers (and does so using clarity color variables)
=> fix(scenariocard): progress bar colors

angular.json
This fixes a file path issue that prevents `npm test` from being run.
=> fix: npm test command

src/app/scenario/terminal.component.ts
This PR fixes a few resource leaks in the terminal component (intervals, timeouts, WS connections)
=> fix(terminal): cleanup held resources

src/app/app.component.html, src/app/app.component.ts, src/app/scenario/ctr.component.scss, src/app/scenario/ctr.component.ts, src/app/scenario/terminal.component.ts, src/app/services/settings.service.ts
/fixes https://github.com/hobbyfarm/hobbyfarm/issues/208
=> New Setting to disable CTR-Blocks

src/app/app.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/226
=> Logout users after token expiration

src/app/scenario/ctr.component.scss, src/app/scenario/ctr.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/218
=> Add feedback for ctr clicks

src/app/app.component.ts
Fixes an error introduced in https://github.com/hobbyfarm/ui/pull/141
=> Fix logout time

src/app/hf-markdown/hf-markdown.component.ts, src/app/scenario/ctr.component.scss, src/app/scenario/ctr.component.ts, src/app/scenario/ctr.service.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/273
=> Fix issues with CTR / CTF

src/app/hf-markdown/hf-markdown.component.ts, src/app/scenario/ctr.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/276
=>  [Markdown] Use randomized token as cat token

src/app/scenario/scenario.component.html, src/app/scenario/scenario.component.ts
Together with https://github.com/hobbyfarm/gargantua/pull/130
=> Display error message if session could not be created

src/app/app.component.html, src/app/app.component.ts
Create a delete button and checkbox to delete multiple access code
=> 295 create delete menu

package.json, src/app/scenario/step.component.html, src/app/scenario/step.component.scss, src/app/scenario/step.component.ts
Enlarge image in Step component by display it on a Modal
=> Enlarge an Image in Step

.github/workflows/ci.yaml, .github/workflows/pkg.yaml
This PR adds automatic arm64 image builds via github workflow and docker buildx.
**Which issue(s) this PR fixes**:
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/344
=> Enhanced GitHub Workflow with ARM64 Docker Builds

src/app/login/login.component.html, src/app/login/login.component.ts, src/app/services/typedSettings.service.ts, src/app/services/user.service.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/357
needs gargantua PR https://github.com/hobbyfarm/gargantua/pull/162 that installs settings
=> Add checkbox for privacy policy

src/app/scenario/step.component.html, src/app/scenario/step.component.ts
=> Fix Context Reload on Tab selection

src/app/hf-markdown/hf-markdown.component.scss, src/app/scenario/step.component.scss
fixes https://github.com/hobbyfarm/hobbyfarm/issues/386
=> Change cursor to magnifying glass when hovering over images

src/app/login/login.component.css, src/app/login/login.component.html, src/app/login/login.component.ts
needs https://github.com/hobbyfarm/gargantua/pull/166
=> Add imprint to login screen

src/app/login/login.component.html
fixes https://github.com/hobbyfarm/hobbyfarm/issues/396
=> Always display privacy policy link, not only in register tab

src/app/app.module.ts, src/app/login/login.component.css, src/app/login/login.component.html, src/app/login/login.component.ts
Copy of https://github.com/hobbyfarm/ui/pull/180 that resolves all conflicts
What this PR does / why we need it:
Adds functionality to toggle password visibility on login/registration page.
Authored by @LeandroMed
Co-authored-by: @PhilipAB
=> Toggle password visiblity

src/app/scenario/ctr.component.scss, src/dark-theme.css
Change the color of card title in dark mode from black to white
=> Fix Card Title color

src/app/course/course.ts, src/app/home.component.html, src/app/scenario/scenario.component.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts
Works together with the Admin-UI implementation:
https://github.com/hobbyfarm/admin-ui/pull/198
=> Introduce content only scenarios and courses to UI

src/app/scenario/terminal.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/419
=> unsubscribe CTRstream if socket reloads or fails

src/app/scenario/ctr.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/424
Allow Click-to-file  if CTR is disabled
=> Allow Click-to-file if CTR is disabled

src/app/services/verification.service.ts
Adapts decoding of Tasks after Verification to always produce proper utf-8 in order to handle special characters like umlauts
=> Fix decoding for Tasks

src/dark-theme.css
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/449
=> Fix 449: Darkmode improvements

src/app/course/course.ts, src/app/scenario/step.component.html, src/app/scenario/step.component.ts
fixes https://github.com/hobbyfarm/hobbyfarm/issues/453
=> fix: respect courses pauseable flag

src/app/scenario/step.component.html, src/app/scenario/step.component.scss
Fixed issue 472 - if there is no vm in a scenario the view is centered and not stretched over the whole page.
=> added content-only css class

src/app/hf-markdown/hf-markdown.component.ts
=> Add support for HCL to markdown syntax highlighting

src/app/hf-markdown/hf-markdown.component.ts
The quiz tagged code renderer was accidentally removed. This PR readds it.
=> Readd quiz to markdown parser

src/app/app.module.ts
Fix correctly displaying quiz content by adding the quiz component to global parsers.
=> fix: add quiz component to global parsers

src/app/hf-markdown/hf-markdown.component.scss
=> set image width in markdown to max-img-size

src/app/app-routing.module.ts, src/app/app.component.html, src/app/app.component.ts, src/app/app.module.ts, src/app/course/course-card/course-card/course-card.component.html, src/app/course/course-card/course-card/course-card.component.scss, src/app/course/course-card/course-card/course-card.component.ts, src/app/course/course-view/course-view.component.html, src/app/course/course-view/course-view.component.ts, src/app/course/course.ts, src/app/explore/explore.component.html, src/app/explore/explore.component.scss, src/app/explore/explore.component.ts, src/app/home.component.html, src/app/home.component.scss, src/app/home.component.ts, src/app/learning-path/learning-path.component.html, src/app/learning-path/learning-path.component.scss, src/app/learning-path/learning-path.component.ts, src/app/scenario/scenariocard.component.html, src/app/scenario/scenariocard.component.ts, src/app/scenario/step.component.ts, src/app/services/context.service.ts, src/app/services/course.service.ts, src/app/services/sidenav.service.ts
**What this PR does / why we need it:**
Scheduled Event selection on Sidenavigation
New UI Elements for Courses
New UI Elements to support Learnpaths
New Page to show Catalog
**Which issue(s) this PR fixes:**
fixes https://github.com/hobbyfarm/hobbyfarm/issues/390
=> Feat: new course view

src/app/app.component.html, src/app/app.component.ts
Adresses https://github.com/hobbyfarm/hobbyfarm/issues/493
=> If course catalog is empty, hide side nav item 'Explore...'

src/app/scenario/step.component.ts
When finishing a scenario within a course, navigate back to course overview instead of /home
=> feat: Navigate back from scenario to Course

src/app/alert/alert.component.html, src/app/alert/alert.component.ts, src/app/alert/alert.ts, src/app/alert/clr-alert-type.ts, src/app/app.module.ts, src/app/quiz/quiz-label.component.html, src/app/quiz/quiz-label.component.scss, src/app/quiz/quiz.component.html, src/app/quiz/quiz.component.ts
**What this PR does / why we need it:**
- Instead of displaying the current date on certificates, we now display the passing date of a quiz instead.
=> Quiz - Use timestamp from successful quiz attempt on certificate
