hobbyfarm/ui

entrypoint.sh
src/app/login/login.component.ts
src/app/scenario/scenariocard.component.ts
src/app/scenario/step.component.ts
src/app/scenario/terminal.component.ts
src/app/services/scenario.service.ts
src/app/services/scenariosession.service.ts
src/app/services/step.service.ts
src/app/services/user.service.ts
src/app/services/vm.service.ts
src/app/services/vmclaim.service.ts

This adds an `--insecure` flag that will prepend `http://` (and `ws://`) to the backend endpoints. For parity, these changes also prepend the secure versions (`https://` and `wss://`) by default.

add insecure flag

---

src/app/app.module.ts
src/app/scenario/terminal.component.ts
src/environments/environment.ts

Auth0's JWT helper requires an FQDN (*not* URL) to configure whitelisting and blacklisting for injecting auth token into requests. 
Because of the runtime changes, one needs to now pass http(s):// in the environment.server value, which was causing JwtModule to choke.
This PR fixes that issue, by specifying a regex to ignore everything pre-:// (roughly speaking just extracting the fqdn from a url). 
It also includes a fix where terminal.component.ts was missing a reference to environment file

Fix insecure runtime configuration

---

src/app/Session.ts
src/app/app-routing.module.ts
src/app/app.module.ts
src/app/course/course.ts
src/app/home.component.html
src/app/home.component.scss
src/app/home.component.ts
src/app/scenario/scenario.component.ts
src/app/scenario/scenariocard.component.ts
src/app/scenario/step.component.ts
src/app/scenario/vminfo.component.ts
src/app/services/course.service.ts
src/app/services/session.service.ts

These changes add a `course` object which is a collection of `scenarios`. Additionally, it renames `scenariosession` to `session`. VMs should persist over a `session`, which is the `course` if it exists and a `scenario` otherwise.

add course object

---

src/app/scenario/step.component.html
src/app/scenario/step.component.ts

Useful so as to provide a mechanism by which scenarios can be closed instead of finished, thus preserving the session in the case of Courses, where the VMs should remain alive for the duration.

added scenario close button

---

src/app/home.component.ts

Extraneous call to _refresh() in the home page .ts was causing multiple queries for the list of courses and scenarios on the home page.

removed extraneous _refresh() call

---

src/app/login/login.component.html
src/app/login/login.component.ts

Disables the registration button after clicking, to (attempt to) prevent multiple requests from occurring.﻿

Disable registration button after click

---

src/app/scenario/step.component.html
src/app/scenario/step.component.ts
src/app/scenario/terminal.component.html
src/app/scenario/terminal.component.ts

Prevents terminal reconnect on node switch. 
Since calling xterm.fit() with a non-visable terminal results in a thrown error and WebSocket.send() might throw an error if the socket is not defined or in state connected, I implemented a 500ms timeout before calling the resize-function when switching tabs. There might be a more elegant solution for this.  
**Which issue(s) this PR fixes**:
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/146
Fixes https://github.com/hobbyfarm/hobbyfarm/issues/147

Fix for #146 and #147

---

cicd/docker/Dockerfile

This commit fixes the broken pipeline. Using node with tag lts-alpine3.10 will let the pipeline run

Fix pipeline using node:lts-alpine3.10

---

src/app/scenario/step.component.ts
src/styles.scss

This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/156
Markdown Syntax:
~~~
```glossary:Helm
Helm is a cool tool that provides many features
```
~~~
results in

Add glossary markdown renderer

---

src/app/scenario/ctr.component.scss
src/app/scenario/ctr.component.ts
src/app/scenario/ctr.service.ts
src/app/scenario/step.component.ts

This PR adds the ability to limit the ctr executions.
Markdown to limit the number of executions
~~~
```ctr:node01:2
echo Limits to 2 clicks
```
~~~
Markdown for unlimited executions.
~~~
```ctr:node01
echo No Limit
```
~~~
Results in 
This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/102

Limit the clicks for CTR Executions

---

src/app/home.component.html
src/app/home.component.ts
src/app/services/user.service.ts

This PR fixes https://github.com/hobbyfarm/hobbyfarm/issues/14
When the scenarios are being loaded we now display "Loading scenarios" instead of "no Scenarios found".
Also adding and removing access codes now results in the scenarios being loaded without the need to reload the page.
This was a bug where the observers were notified before sending a request to gargantua. Now the subscribers are notified after the request is done.

Improve loading scenarios after changing access codes

---

src/app/home.component.html

Removes the course ID from the course header on the course selection page.
Before: c-iur5emp4m3 - Coursename
After: Coursename
Fixes svalabs/ui#18

Remove course ID from course header

---

src/app/app.component.html

Fixes the following error that occurs in the browser console:
If you define both a name and a formControlName attribute on your radio button, their values must match.
Ex: <input type="radio" formControlName="food" name="food">
The old `name` attribute is not referenced anywhere in this repository, so this should be safe.
The bug was probably introduced in #90

Fix error related to input name mismatch

---

src/app/scenario/step.component.html
src/app/scenario/step.component.scss
src/app/scenario/step.component.ts

In the existing code, the implementation of the Markown renderer had been extended for simple things like styling generated DOM Elements or adding a `target="_blank"` to links, so they open in new windows/tabs.
This PR moves element styles to a SCSS file and implements the "open all links in new tab" feature by leveraging event bubbling. This way, error prone and repetitive string manipulation can be avoided.

Simpler Markdown rendering

---

src/app/course/course.ts
src/app/home.component.html

The type of the `scenarios` field in the `Course` type did not match what we get from the server.
This PR fixes the type and uses a more obvious variable name in a template.

fix(Course): align scenarios type w/ reality

---

src/app/scenario/terminal.component.ts
src/tsconfig.app.json
src/tsconfig.spec.json
src/types.d.ts

This rephrases the TS from commit ccc22cd37d79 so that we do not need to define any custom types.
CC @PhilipAB

Simplify "Use DOM renderer for Firefox. (#89)"

---

src/app/scenario/step.component.ts

This replaces usage of `_.escape` with our own implementation.
This has the following advantages:
- no (undeclared) dependency on `lodash`
- 500kB smaller vendor bundle (in dev build)
- no warnings about optimization bailout during builds or in browser console

Remove undeclared dependency on lodash

---

src/app/app.component.html
src/app/app.component.ts
src/app/scenario/terminal-themes/themes.ts
src/app/scenario/terminal.component.ts
src/app/services/settings.service.ts
src/app/services/user.service.ts

Code cleanup regarding all things related to user settings. Also sets the stage for another PR that I am preparing.
- refactor: simpler theme settings logic
- refactor: make terminal themes readonly
- refactor: use BehaviorSubject as cache
- refactor: move updateSettings
- refactor: settings service methods
- refactor: use typed settings
- refactor: allow updating settings w/ a partial
- feat: use cached settings once loaded

refactor: cleanup settings code

---

src/app/scenario/scenariocard.component.ts

When the max_step is greater than the total_step the wrong color is displayed.

Fix progress color when step is over total steps

---

src/app/services/gargantua.service.ts
src/app/services/user.service.ts

The changes from #116 did not conform to the stricter TypeScript requirements from #122.

fix: type conflicts between #116 and #122

---

src/app/home.component.html
src/app/home.component.ts
src/app/scenario/PrintableScenario.ts
src/app/scenario/Scenario.ts
src/app/scenario/scenariocard.component.html
src/app/scenario/scenariocard.component.ts

This somewhat simplifies the printable feature introduced in #117. Together with the upcoming changes in Gargantua by @PhilipAB, this fixes print buttons for scenarios in courses.
However, this can be merged independently from the Gargantua changes.

Cleanup after printable feature

---

src/app/home.component.html
src/app/services/gargantua.service.ts

This fixes a bug that was introduced in #125 and that causes a broken UI when there are no scenarios available to the logged-in user.
CC @jggoebel

fix: handle "no scenarios" case

---

src/app/app-config.service.ts
src/app/app.component.css
src/app/app.component.html
src/app/app.component.ts
src/config.json

- UI implementation to make the about section customizable
- Changed default values
The current default modal now looks like this:
Changing the about title or body text removes the default button automatically, e.g.:

About config

---

src/app/scenario/step.component.ts

This bug leads to the wrgon terminal being loaded when no protocol is ste in the vm templates.
Now the terminal defaults to SSH

Fix unset protocol bug

---

.github/workflows/main.yaml

to prevent pipeline failing on new release

Tag latest image

---

src/app/hf-markdown/hf-markdown.component.scss
src/app/hf-markdown/hf-markdown.component.ts
src/app/scenario/ctr.component.scss
src/app/scenario/step.component.ts

In Step Content Markdown `${session}` will print the current Session ID.
Also edited the inline codeblocks to align with the style of other codeblocks
Before this change:
After this change:

Add style for inline codeblocks, ability to print session id in md

---

src/app/hf-markdown/hf-markdown.component.scss

Style for inline code blocks was not using the right css selector. 
With this PR we can use inline code inside ul and ol (numbered lists and lists)
fixes https://github.com/hobbyfarm/hobbyfarm/issues/278

[Markdown] Inline-code style for ul, ol

---

src/app/hf-markdown/hf-markdown.component.ts
src/app/scenario/scenariocard.component.ts
src/app/scenario/step.component.html
src/app/scenario/step.component.ts

Services that do not have a Tab in the UI get a Tab anyways as long as they are selected by the User.
Except from the currently selected Tab all Tabs can now be pushed to the Overflow-Dropdown, if there isn't enough space to show all of them.
Addresses https://github.com/hobbyfarm/hobbyfarm/issues/288 and https://github.com/hobbyfarm/hobbyfarm/issues/285

Improve service-tabs

---

src/app/app.component.html
src/app/app.component.ts

This is needed to be able to display the privacy policy after login.
(second part of https://github.com/hobbyfarm/hobbyfarm/issues/396 )

Display privacy policy in the burger menu

---

src/app/app.component.html
src/app/app.component.ts
src/app/scenario/step.component.html
src/app/scenario/step.component.ts
src/app/services/settings.service.ts

Saves the divider position (percentage of the content on the left side) to the user settings and restores it when reloading.
This way a user can set their preffered divider position.
The user can also set the value in the settings directly.
fixes https://github.com/hobbyfarm/hobbyfarm/issues/404

Save divider position to user settings

---

src/app/scenario/guacTerminal.component.ts
src/app/scenario/step.component.html
src/app/scenario/step.component.ts
src/app/scenario/terminal.component.ts

Let the user reload the terminal without reloading the whole page.
For example when he accidentally crashes the connection by executing "exit" or if any other error causes a connection issue

Added button to reload Terminal 

---

src/app/app.component.html
src/app/app.component.scss
src/app/app.component.ts
src/app/app.module.ts
src/app/home.component.html
src/app/home.component.scss
src/app/home.component.ts
src/app/services/context.service.ts
src/app/services/user.service.ts
src/data/ScheduledEvent.ts

Show the scheduled event end_time in the accesscode modal:
The description is not yet displayed and we might need to think about if can display the scheduled event end_time of the active event somewhere else more present
Needs:
https://github.com/hobbyfarm/gargantua/pull/173

Display how much time is left in ScheduledEvents

---

src/app/scenario/guacTerminal.component.ts

This PR suggests a simple automatic reload mechanism on tunnel errors.
During a test run on Windows scenarios, we had some tunnel errors which were frequently occuring. It would be nice if the client would at least try a few reconnects automatically so that the user does not need to reload the tab manually.
This PR is in draft mode because we need to clarify the following things:
- should we also implement a retry logic for client connection errors?
- which interval(s) should we choose for our retry logic?

Implement automatic retry-mechanism for TunnelErrors

---

src/app/app.module.ts
src/app/hf-markdown/copy-to-clipboard/copy-to-clipboard.component.html
src/app/hf-markdown/copy-to-clipboard/copy-to-clipboard.component.scss
src/app/hf-markdown/copy-to-clipboard/copy-to-clipboard.component.ts
src/app/hf-markdown/hf-markdown.component.ts
src/app/scenario/ctr.service.ts

fixes https://github.com/hobbyfarm/hobbyfarm/issues/333
Adds a copy to clipboard icon to codeblocks that are not Click-To-File
~~~
```yaml:test.yml
Dateiinhalt: Test
Kopier mich doch
```
~~~
Uses the https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API to write the code to the clipboard.

Copy code to clipboard

---

src/app/scenario/guacTerminal.component.ts

This PR fixes the resizing for the guac terminal.
For certain display resolutions, the use of Math.floor resulted in the scaling factor being reduced to zero.

Fix display resizing

---

package-lock.json
package.json

Before, the guacamole-common-js dependency was resolved to my personal npm package. Now it is reflecting the `hobbyfarm-org` release instead.

Switch guacamole-common-js reference to hobbyfarm-org

---

src/app/course/course-view/course-view.component.ts
src/app/scenario/step.component.ts

Course View used takeUntilDestroyed outside an injection context. Refactored to not use takeUntilDestroyed. 
Content Only Scenarios now do respect if the VM for a course should be kept on Finish

fix: course view, keepVM with content only scenarios
